# Generated by Django 5.1.1 on 2026-09-21 14:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('internal_length', models.DecimalField(decimal_places=2, help_text='Internal length in centimeters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('internal_width', models.DecimalField(decimal_places=2, help_text='Internal width in centimeters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('internal_height', models.DecimalField(decimal_places=2, help_text='Internal height in centimeters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_weight', models.DecimalField(decimal_places=3, help_text='Maximum contents weight limit in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('empty_weight', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), help_text='Empty box tare weight in kilograms (ignored for limit by default)', max_digits=10, null=True)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Box unit cost', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Boxes',
                'ordering': ['cost', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('internal_length__gt', 0)), name='box_internal_length_gt_zero'), models.CheckConstraint(condition=models.Q(('internal_width__gt', 0)), name='box_internal_width_gt_zero'), models.CheckConstraint(condition=models.Q(('internal_height__gt', 0)), name='box_internal_height_gt_zero'), models.CheckConstraint(condition=models.Q(('max_weight__gt', 0)), name='box_max_weight_gt_zero'), models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='box_cost_gte_zero')],
            },
        ),
        migrations.CreateModel(
            name='BoxRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_status', models.CharField(max_length=50)),
                ('payload', models.JSONField(help_text='Full audit explanation JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='boxes.box')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='boxes.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in centimeters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in centimeters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in centimeters', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sku'],
                'constraints': [models.CheckConstraint(condition=models.Q(('length__gt', 0)), name='product_length_gt_zero'), models.CheckConstraint(condition=models.Q(('width__gt', 0)), name='product_width_gt_zero'), models.CheckConstraint(condition=models.Q(('height__gt', 0)), name='product_height_gt_zero'), models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='product_weight_gt_zero')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units', validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boxes.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='boxes.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orderitem_quantity_gt_zero')],
                'unique_together': {('order', 'product')},
            },
        ),
    ]
